version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: spatial_postgres
    environment:
      POSTGRES_DB: spatial_data
      POSTGRES_USER: spatial_user
      POSTGRES_PASSWORD: spatial_pass
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: spatial_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST_TEST: db
      DB_PORT_TEST: 5432
      DB_USERNAME_TEST: spatial_user
      DB_PASSWORD_TEST: spatial_pass
      DB_DATABASE_TEST: spatial_data
      CA_CERT_PATH: dummy_cert.pem  # Replace if needed or mount the real cert
    env_file:
      - .env

volumes:
  pg_data:
